name: WES
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Default bismark
  - fastp=0.23.2
  - fastqc=0.11.9
  - bwa=0.7.17
  - samtools=1.15
  - vcflib=1.0.3
  - picard=2.26.11
  - nextflow=21.10.6
